### ISSUE TITLE
Please update the demo URL under your README.md (from http:// to https://)

### ISSUE THREAD

**Issue by ax4** [dwa012/html5-qrcode#57]
People maybe scared when they first click the demo link, but nothing show up in some browser (due to the getUserMedia() limit by the browser)

**Comment by thatneat** [comment]
+1; your demo does not work at http://dwa012.github.io/html5-qrcode/ but it does work at https://dwa012.github.io/html5-qrcode/ because getUserMedia() doesn't work on non-secure connections
