### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by jmmccota** [dwa012/html5-qrcode#59]
I'm getting error on callback call https://github.com/dwa012/html5-qrcode/blob/master/src/html5-qrcode.js#L65

How can i fix this?

**Comment by ravi2432** [comment]
I got same issue. Can you please resolve it

**Comment by jat10** [comment]
@jmmccota you need to add this script `https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/jsqrcode-combined.min.js` before 
```
<script type="text/javascript" src="html5-qrcode.min.js"></script>
```

**Comment by jmmccota** [comment]
still giving error.
